PREP(correctUnit);
PREP(handleLambsSwitchMove);
PREP(handleUnitAnimStateChanged);
PREP(handleUnitLocal);
PREP(handleZenSetUnitPos);
PREP(init);
PREP(isEligibleUnit);
PREP(monitorUnits);
PREP(registerUnit);
